name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/teclados/logitech.png
    - assets/images/teclados/razer.png
    - assets/images/teclados/reddragon.png
    - assets/images/Monitores/acer.png
    - assets/images/Monitores/msi.png
    - assets/images/Monitores/masterg.png
    - assets/images/Mouses/logitechg203.png
    - assets/images/Mouses/razermini.png
    - assets/images/Mouses/logitechg502.png
    - assets/images/Audifonos/hyperx.png
    - assets/images/Audifonos/razerkraken.png
    - assets/images/Audifonos/reddragon.png
